"""empty message

Revision ID: a35df9119125
Revises: f9e72235522b
Create Date: 2025-01-27 02:16:04.512947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a35df9119125'
down_revision = 'f9e72235522b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('physiotherapists', sa.Column('city', sa.String(length=50), nullable=False))
    op.drop_column('physiotherapists', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physiotherapists', sa.Column('location', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('physiotherapists', 'city')
    op.drop_column('patients', 'city')
    # ### end Alembic commands ###
