"""empty message

Revision ID: f9e72235522b
Revises: 22004b2e804f
Create Date: 2025-01-26 23:11:53.879883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e72235522b'
down_revision = '22004b2e804f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('physiotherapists', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('physiotherapists', 'password_hash')
    op.drop_column('patients', 'password_hash')
    # ### end Alembic commands ###
